import torch
import triton
import triton.language as tl


@triton.jit
def bincount_kernel(x_ptr, counts_ptr, N, BLOCK: tl.constexpr):
    pid = tl.program_id(0)
    offsets = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offsets < N
    # Load flattened values; assume values are int32 (as in get_inputs)
    vals = tl.load(x_ptr + offsets, mask=mask, other=0)  # int32
    # Atomic add into counts[vals] for i in 0..255
    # We assume vals in [0, 255], as generated by get_inputs with num_experts=256.
    for i in range(256):
        # For masked lanes, vals may be 0 due to 'other=0', but we must avoid atomic_add when mask is False.
        # Create a mask based on i being valid bin index and loaded offsets being valid.
        # Since 'other=0' for invalid offsets, and vals==0 implies count for bin 0, we need to guard with mask.
        # We can use mask and vals==i to gate atomic_add.
        eq = (vals == i) & mask
        # Atomic add 1 for each lane where eq is True
        tl.atomic_add(counts_ptr + i, eq.to(tl.int32))


@triton.jit
def inclusive_prefix_sum_kernel(x_ptr, y_ptr, L: tl.constexpr):
    # L is known at launch (257). Compute inclusive prefix sum: y[0]=x[0], y[1]=x[0]+x[1], ..., y[L-1]=sum(x[:])
    # We write int64 results. Triton supports int64 arithmetic.
    # First element is x[0]
    x0 = tl.load(x_ptr + 0)  # int32
    tl.store(y_ptr + 0, x0.to(tl.int64))
    # Initialize accumulator with x0 (cast to int64)
    acc = x0.to(tl.int64)
    # Loop i from 1 to L-1
    # Triton supports while loops; use a fixed-iteration loop via range(1, L) is not available, so we do while.
    i = 1
    while i < L:
        vi = tl.load(x_ptr + i)  # int32
        acc = acc + vi.to(tl.int64)
        tl.store(y_ptr + i, acc)
        i += 1


class ModelNew(torch.nn.Module):
    def forward(self, topk_idx: torch.Tensor):
        # Flatten to 1D (N = batch_size * seq_len * num_experts_per_tok)
        flat = topk_idx.reshape(-1)
        N = flat.numel()

        # 1) Triton bincount into counts[0:256] (int32), assuming values in [0, 255]
        counts = torch.zeros(256, dtype=torch.int32, device=flat.device)
        BLOCK = 1024
        grid = (triton.cdiv(N, BLOCK),)
        bincount_kernel[grid](flat, counts, N, BLOCK=BLOCK)

        # 2) Triton inclusive prefix sum to produce offsets (length 257, int64)
        offsets = torch.empty(257, dtype=torch.int64, device=flat.device)
        offsets[0] = 0  # inclusive prefix sum starting at 0
        inclusive_prefix_sum_kernel[(1,)](counts, offsets, L=257)

        # 3) Use PyTorch for stable argsort of flattened indices (returns permutation of [0, N-1])
        #    This exactly matches the original function's output for sorted_token_indices.
        sorted_token_indices = flat.argsort(stable=True).to(torch.int32)

        return sorted_token_indices, offsets